version: '3.8'

services:
  playlist-app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: playlist-app-prod
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      # Mount music directories
      - ${MUSIC_DIRECTORY:-./music}:/music:ro
      - ${AUDIO_DIRECTORY:-./audio}:/audio:ro
      
      # Optional: Mount additional music directories
      - ${EXTRA_MUSIC_DIRS:-}:/extra_music:ro
    depends_on:
      - redis
    restart: unless-stopped

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: playlist-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: playlist-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - playlist-app
    restart: unless-stopped
    profiles:
      - nginx

volumes:
  redis_data:
    driver: local
