version: '3.8'

services:
  playlist-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: playlist-app-dev
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      # Mount music directories
      - ${MUSIC_DIRECTORY:-./music}:/music:ro
      - ${AUDIO_DIRECTORY:-./audio}:/audio:ro
      
      # Development: Mount source code for live reload
      - ./src:/app/src
      - ./main.py:/app/main.py
      - ./scripts:/app/scripts
      - ./tests:/app/tests
      
      # Logs directory
      - ./logs:/app/logs
      
      # Optional: Mount additional music directories
      - ${EXTRA_MUSIC_DIRS:-}:/extra_music:ro
    restart: unless-stopped
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  # CLI service for running commands
  playlist-cli:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: playlist-cli
    env_file:
      - .env
    volumes:
      - ${MUSIC_DIRECTORY:-./music}:/music:ro
      - ${AUDIO_DIRECTORY:-./audio}:/audio:ro
      - ./src:/app/src
      - ./scripts:/app/scripts
      
      # Logs directory
      - ./logs:/app/logs
    profiles:
      - cli
    command: ["python", "playlist_cli.py"]
